### ISSUE TITLE
关于“哑终端”的疑问

### ISSUE THREAD

**Issue by xuzf-git** [spencerwooo/bitsrun-rs#9]
学长我有几个问题请教一下：
1. 校园网环境下的哑终端是什么含义？
2. 实验室的服务器算不算哑终端？
3. 登记哑终端之后会有什么影响？

**Comment by spencerwooo** [comment]
> 感谢学长解答，还有就是哑终端的登记是只有老师的账号有权限吗？

对，是需要教职工账号的。要是有更多需要建议直接联系网络中心的老师，我们之前还遇到静态 IP 的绑定问题，也需要网络中心那边操作。
